Math Operations

In [8]:
a = [1, 2, 3]
b = [4, 5, 6]

a + b

[1, 2, 3, 4, 5, 6]

In [9]:
import numpy as np

In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a + b

array([5, 7, 9])

In [12]:
print (a - b)
print (a * b)
print (a / b)

[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Comparison

In [15]:
print (a > b)
print (a < b)
print (a == b)

[False False False]
[ True  True  True]
[False False False]


Logical Operator

In [18]:
x = np.array([True, False, True])
y = np.array([False, False, True])

print (np.logical_and(x, y))
print (np.logical_or(x, y))
print (np.logical_not(x))

[False False  True]
[ True False  True]
[False  True False]


Bitwise Operator

In [21]:
a = np.array([1, 2, 3])
b = np.array([0, 1, 1])

print (np.bitwise_and(a, b))
print (np.bitwise_or(a, b))

[0 0 1]
[1 3 3]


Modulus and Power

In [22]:
10 % 3

1

In [23]:
10 ** 3

1000

In [ ]:
a = np.array([10, 20, 30])
b = np.array([3, 7, 4])

print (np.mod(a, b)) # a % b
print (np.power(a, b)) # a ** b

[1 6 2]
[      1000 1280000000     810000]


In [26]:
a % b

array([1, 6, 2])

In [27]:
a ** b

array([      1000, 1280000000,     810000])

Scalar Operations

Fahrenheit = Celsius * 9 / 5 + 32

In [28]:
celsius = [0, 10, 20, 30]
fahrenheit = celsius * 9 / 5 + 32

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [31]:
celsius = np.array([0, 10, 20, 30])

fahrenheit = celsius * 9 / 5 + 32

print(fahrenheit)

[32. 50. 68. 86.]


Math functions

In [41]:
a = np.array([1, 2, 3, 4])

print (np.sqrt(a))
print (np.exp(a))
print (np.log(a))
print (np.sin(a))

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [56]:
# sigmoid function <- Machine Learning
### x -> 1 / (1 + e^-x)

x = np.array([-1, 0, 1])
y = 1 / (1 + np.exp(-x))

print (y)

[0.26894142 0.5        0.73105858]


Aggregation Functions

In [57]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [58]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
print (np.sum(a))

21


In [61]:
print (np.sum(a, axis=0))

[5 7 9]


In [62]:
print (np.sum(a, axis=1))

[ 6 15]


In [63]:
print (np.sum(a))
print (np.mean(a))
print (np.std(a))
print (np.min(a))
print (np.max(a))

21
3.5
1.707825127659933
1
6


Dot Product

In [64]:
house = np.array([
    [1200, 3, 1],
    [1200, 3, 0],
    [1000, 3, 0],
    [1000, 1, 1]
])

In [65]:
w = np.array([200, 10000, 50000])

In [66]:
print (house.shape)
print (w.shape)

(4, 3)
(3,)


In [67]:
print (np.dot(house, w))

[320000 270000 230000 260000]


In [ ]:
house * w

array([[240000,  30000,  50000],
       [240000,  30000,      0],
       [200000,  30000,      0],
       [200000,  10000,  50000]])

In [70]:
np.sum(house * w, axis=1)

array([320000, 270000, 230000, 260000])

In [71]:
A = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
B = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

In [75]:
print (A.shape)
print (B.shape)
print (B.T.shape)

(2, 4)
(2, 4)
(4, 2)


In [74]:
print (np.dot(A, B))

ValueError: shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)

In [76]:
print (np.dot(A, B.T))

[[30 30]
 [30 30]]


In [77]:
A

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [78]:
B.T

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [79]:
print (A @ B.T)

[[30 30]
 [30 30]]


Broadcasting

In [80]:
a = np.array([1, 2, 3])
b = np.array([[10], [20]])

In [82]:
print (a.shape)
print (b.shape)

(3,)
(2, 1)


In [85]:
a

array([1, 2, 3])

In [86]:
b

array([[10],
       [20]])

In [84]:
a + b

array([[11, 12, 13],
       [21, 22, 23]])

Creating Arrays from Existing Data

In [89]:
a = [1,2,3,4] # List
b = ([[1,2], [2,3]]) # Tuple -> 2D List
c = (10,20,30) # Tuple

In [90]:
a_npy = np.array(a)
print(a_npy, a_npy.dtype, type(a))

[1 2 3 4] int64 <class 'list'>


In [91]:
b_npy = np.array(b)
print(b_npy, b_npy.dtype, type(b))

[[1 2]
 [2 3]] int64 <class 'list'>


In [92]:
c_npy = np.array(c)
print(c_npy, c_npy.dtype, type(c))

[10 20 30] int64 <class 'tuple'>


Let's do some Stack

In [93]:
a = np.array([[1,2]])
b = np.array([[3,4]])

In [96]:
a

array([[1, 2]])

In [97]:
b

array([[3, 4]])

In [95]:
# vstack

print (np.vstack((a, b)))

[[1 2]
 [3 4]]


In [98]:
# hstack

print (np.hstack((a, b)))

[[1 2 3 4]]


np.char

In [99]:
a = np.array(['hello', 'world'])
b = np.array(['_user', '_123'])

In [101]:
print (np.char.add(a, b))

['hello_user' 'world_123']


In [104]:
print (np.char.multiply(a, 3))

['hellohellohello' 'worldworldworld']


In [111]:
a = np.array(['helloo', 'WORLD'])

print(np.char.upper(a)) 
print(np.char.lower(a)) 
print(np.char.capitalize(a)) 

['HELLOO' 'WORLD']
['helloo' 'world']
['Helloo' 'World']


In [112]:
print(np.char.center(a, 11, fillchar='*'))

['***helloo**' '***WORLD***']


In [113]:
a = np.array(['data_science', 'machine_learning'])

In [114]:
print (np.char.replace(a, "_", " "))

['data science' 'machine learning']


In [115]:
print (np.char.split(a, sep="_"))

[list(['data', 'science']) list(['machine', 'learning'])]


In [120]:
print (np.char.find(a, "_"))
print (np.char.find(a, "a"))
print (np.char.find(a, "z"))
print (np.char.find(a, "learn"))

[4 7]
[1 1]
[-1 -1]
[-1  8]


In [121]:
a

array(['data_science', 'machine_learning'], dtype='<U16')

In [127]:
print(np.char.count(a, 'a'))
print(np.char.count(a, 'data'))
print(np.char.count(a, 'data_s'))
print(np.char.count(a, 'data s'))

[2 2]
[1 0]
[1 0]
[0 0]


Statistical Functions

In [128]:
data = np.array([1, 2, 3, 4, 5, 6])

In [130]:
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Variance:", np.var(data))

print("Min:", np.min(data))
print("Max:", np.max(data))

Mean: 3.5
Median: 3.5
Standard Deviation: 1.707825127659933
Variance: 2.9166666666666665
Min: 1
Max: 6


In [131]:
print("Argmin:", np.argmin(data))
print("Argmax:", np.argmax(data))

Argmin: 0
Argmax: 5


In [142]:
data = np.array([1, 3, 5, 7, 9])
print(np.percentile(data, 50)) # range 1 - 100
print(np.quantile(data, 1)) # range 0 - 1

5.0
9


In [132]:
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])

print(np.mean(matrix, axis=0)) # Column
print(np.mean(matrix, axis=1)) # Row

[2.5 3.5 4.5]
[2. 5.]


sort, search and counting functions

In [143]:
arr = np.array([3, 6, 1, 1, 1, 1, 8, 2, 5, 6])

In [ ]:
print("Sorted:", np.sort(arr))
print("Unique elements:", np.unique(arr))
print("Sorted indices:", np.argsort(arr)) # [1 1 1 1 2 3 5 6 6 8]
print("Count of each element:", np.bincount(arr)) # 0->0, 1->4, 2->1, 3->1, 4->0, 5->1, 6->2, 7->0, 8->1

Sorted: [1 1 1 1 2 3 5 6 6 8]
Unique elements: [1 2 3 5 6 8]
Sorted indices: [3 2 5 4 7 0 8 1 9 6]
Count of each element: [0 4 1 1 0 1 2 0 1]


In [148]:
arr = np.array([1, 2, 3, 4])

for x in arr:
    print(x)

1
2
3
4


In [149]:
arr_2d = np.array([[1, 2], [3, 4]])

for x in arr_2d:
    print(x)

[1 2]
[3 4]


In [151]:
np.nditer(arr_2d)

In [150]:
for x in np.nditer(arr_2d):
    print(x)

1
2
3
4


Duplicate

In [152]:
a = np.array([1, 2, 3])

In [153]:
b = a

In [154]:
a

array([1, 2, 3])

In [155]:
b

array([1, 2, 3])

In [156]:
b[0] = 100

In [157]:
b

array([100,   2,   3])

In [158]:
a

array([100,   2,   3])

In [159]:
print (id(a))
print (id(b))

2196000123152
2196000123152


In [160]:
a = np.array([1, 2, 3])

In [162]:
b = a.copy()

In [163]:
a

array([1, 2, 3])

In [164]:
b

array([1, 2, 3])

In [166]:
b[0] = 100

In [167]:
b

array([100,   2,   3])

In [168]:
a

array([1, 2, 3])

In [169]:
print (id(a))
print (id(b))

2196000127760
2196000160624


In [ ]:
a = np.array([1, 2, 3])

b = a.view() # Similar to b = a but in different memory position

c = a.copy()

In [171]:
print (a)
print (b)
print (c)

[1 2 3]
[1 2 3]
[1 2 3]


In [172]:
b[0] = 10

print (a)
print (b)
print (c)

[10  2  3]
[10  2  3]
[1 2 3]


In [173]:
c[0] = 20

print (a)
print (b)
print (c)

[10  2  3]
[10  2  3]
[20  2  3]


In [ ]:
a = np.arange(5) # [0, 1, 2, 3, 4]

b = a[1:4] # View -> [1, 2, 3]

print(np.shares_memory(a, b))

True


In [190]:
a = np.arange(5) # [0, 1, 2, 3, 4]

b = a[1:4].copy() # Copy -> [1, 2, 3]

print(np.shares_memory(a, b))

False


In [193]:
a = np.array([[1, 2], [3, 4]])
print (a)
print(a.ravel())
print(a.flatten())

[[1 2]
 [3 4]]
[1 2 3 4]
[1 2 3 4]
