In [12]:
import numpy as np

np.zeros()

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros((5, 5)).shape

(5, 5)

In [16]:
np.zeros((5, 5)).ndim

2

np.ones()

In [17]:
np.ones(3)

array([1., 1., 1.])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.ones((3,4), dtype=np.int8)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

np.full()

In [20]:
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [21]:
np.full((3, 4), 2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

np.eye()

In [22]:
np.eye(6, 6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [23]:
np.eye(6, 6, 3)

array([[0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

np.random.rand()

In [29]:
np.random.rand(5, 5)

array([[0.24330854, 0.41200555, 0.74037878, 0.67646464, 0.50789267],
       [0.20584576, 0.51660347, 0.78660683, 0.75659237, 0.15116485],
       [0.44564432, 0.26295411, 0.07601309, 0.51085213, 0.77818379],
       [0.30646193, 0.99474953, 0.03359847, 0.69603776, 0.08033256],
       [0.36905135, 0.04969524, 0.9878155 , 0.4216329 , 0.451229  ]])

In [31]:
a = np.random.rand(5, 5) * 10

In [32]:
a

array([[2.83833876, 6.63958378, 3.31456042, 3.58408197, 6.33156015],
       [5.34720337, 6.03333479, 2.60417011, 0.09019245, 3.42696436],
       [8.5138673 , 4.30935641, 9.91783923, 5.20346994, 4.02327545],
       [4.59497856, 7.25564046, 1.6772278 , 5.5878992 , 9.22043498],
       [3.28036   , 7.30012535, 2.76513234, 0.69926298, 4.2980529 ]])

In [33]:
a = a.tolist()

In [34]:
a

[[2.838338755260775,
  6.639583781204195,
  3.314560420932678,
  3.584081970743748,
  6.331560151115159],
 [5.347203372276585,
  6.033334788996509,
  2.604170109635234,
  0.09019245045058577,
  3.426964362973698],
 [8.513867303108405,
  4.309356412294547,
  9.917839229444676,
  5.2034699359915315,
  4.023275452420599],
 [4.594978563184054,
  7.255640459863901,
  1.6772278039271171,
  5.587899198300291,
  9.220434980177059],
 [3.280359997061847,
  7.300125353669788,
  2.765132340285774,
  0.6992629760187841,
  4.2980529027847005]]

In [42]:
b = np.random.rand(10)

b = b * 10

b = b.tolist()

b = [int(i) for i in b]

b

[0, 1, 2, 9, 7, 6, 2, 8, 1, 4]

In [43]:
np.random.randn(10)

array([ 0.29789245,  0.74403127,  1.35193007, -0.32592031,  0.36388107,
       -0.0694062 , -0.81191169,  0.48795773,  0.21173969,  1.5611725 ])

In [45]:
np.random.randint(1, 11, 15)

array([ 9,  5,  9,  2,  6,  2,  9,  8,  7,  7,  7, 10,  4, 10,  7],
      dtype=int32)

Numpy Attributes

In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [47]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
arr.shape

(2, 3)

In [49]:
arr.ndim

2

In [50]:
arr.dtype

dtype('int64')

In [52]:
arr.itemsize # size in bytes of one element

8

In [53]:
arr.nbytes

48

In [54]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [56]:
arr.shape

(2, 3)

In [57]:
arr.T.shape

(3, 2)

Indexing and Slicing

In [59]:
arr = np.array([10, 20, 30, 40, 50, 60])

In [60]:
arr

array([10, 20, 30, 40, 50, 60])

In [61]:
arr[0]

np.int64(10)

In [62]:
arr[1]

np.int64(20)

In [63]:
arr[5]

np.int64(60)

In [66]:
arr[-1]

np.int64(60)

In [67]:
arr[::2]

array([10, 30, 50])

In [68]:
mat = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
)

In [69]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [71]:
print (mat[0, 1])

2


In [72]:
print (mat[0])

[1 2 3]


In [73]:
print (mat[:, 2])

[3 6 9]


In [74]:
print (mat[:, -1])

[3 6 9]


In [78]:
print (mat[1:3, 1:3])

[[5 6]
 [8 9]]


In [79]:
print (mat[::-1, ::-1])

[[9 8 7]
 [6 5 4]
 [3 2 1]]


Operations

In [80]:
arr = np.array([5, 10, 15, 20, 25])

In [81]:
print (arr)

[ 5 10 15 20 25]


In [82]:
arr > 10

array([False, False,  True,  True,  True])

In [83]:
arr[arr > 10]

array([15, 20, 25])

In [84]:
index = [0, 3, 4]

print (arr[index])

[ 5 20 25]


In [87]:
idx = np.where(arr > 10)

In [88]:
arr[idx]

array([15, 20, 25])

Reshaping and Resizing

In [89]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [90]:
arr.shape

(6,)

In [91]:
reshaped = arr.reshape(2, 3)

In [92]:
reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
reshaped.shape

(2, 3)

In [94]:
arr = np.array([1, 2, 3, 4, 5, 6,7,8,9,10,11,12])

In [97]:
reshaped = arr.reshape(3, -1)

In [98]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [99]:
a = np.array([[1, 2], [3, 4]])

In [100]:
print (a)

[[1 2]
 [3 4]]


In [101]:
b = a.flatten()

In [102]:
b

array([1, 2, 3, 4])

In [112]:
a = np.array([1, 2, 3, 4])

In [111]:
a.reshape(2, 3)

ValueError: cannot reshape array of size 4 into shape (2,3)

In [113]:
a.resize((2, 3))

In [114]:
a

array([[1, 2, 3],
       [4, 0, 0]])

3 Dimensional

In [115]:
a = np.array([[[1],[2],[3]], [[1],[2],[3]]])

In [116]:
a

array([[[1],
        [2],
        [3]],

       [[1],
        [2],
        [3]]])

In [117]:
print (a.shape)

(2, 3, 1)


In [118]:
print (a.ndim)

3


In [119]:
b = np.squeeze(a)

In [120]:
b

array([[1, 2, 3],
       [1, 2, 3]])

In [121]:
b.shape

(2, 3)

In [122]:
a = np.array([
                [1,2,3],
                [1,2,3],
                [1,2,3]
            ])

In [123]:
print (a)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [124]:
print (np.sum(a, axis=0))

[3 6 9]


In [125]:
print (np.sum(a, axis=1))

[6 6 6]
