In [2]:
import numpy

In [3]:
!pip install numpy

In [4]:
import numpy as np
import time

In [5]:
a = list(range(100000000))
b = list(range(100000000))

In [10]:
# Using List

start_time_1 = time.time()
c = [i + j for i, j in zip(a,b)]
end_time_1 = time.time()

time_taken_1 = end_time_1 - start_time_1

print (f"Time Taken = {time_taken_1}")

Time Taken = 35.02870178222656


In [11]:
a = np.array(a)
b = np.array(b)

In [12]:
# Using Numpy

start_time_2 = time.time()
d = a + b
end_time_2 = time.time()

time_taken_2 = end_time_2 - start_time_2

print (f"Time Taken = {time_taken_2}")

Time Taken = 10.27835202217102


In [14]:
time_taken_1 / time_taken_2

3.408007597586418

1. np.array()

In [15]:
array1 = [1, 2, 3]

np_array1 = np.array(array1)

In [16]:
array1

[1, 2, 3]

In [17]:
np_array1

array([1, 2, 3])

In [18]:
type(array1)

list

In [19]:
type(np_array1)

numpy.ndarray

In [20]:
type(np_array1[0])

numpy.int64

In [21]:
np_array2 = np.array(array1, dtype=np.int8)

In [23]:
type(np_array2[0])

numpy.int8

In [24]:
np_array3 = np.array(array1, dtype=np.float16)

In [25]:
type(np_array3[0])

numpy.float16

2. np.arange(start, stop, step)

In [26]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

3. np.linspace(start, stop, num)

In [28]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

4. np.zeros(shape)

In [35]:
npz1 = np.zeros(5)

print (npz1)
print (npz1.ndim)

[0. 0. 0. 0. 0.]
1


In [36]:
npz2 = np.zeros((5, 3))

print (npz2)
print (npz2.ndim)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2


In [37]:
npz3 = np.zeros((5, 3, 2))

print (npz3)
print (npz3.ndim)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
3
